//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocetniZaslon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bankovni_racun
    {
        public string iban { get; set; }
        public int id_vrsta_racuna { get; set; }
        public int id_korisnik { get; set; }
        public string naziv_racuna { get; set; }
        public Nullable<decimal> stanje_racuna { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Vrsta_racuna Vrsta_racuna { get; set; }
    }
}
