//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocetniZaslon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bankovni_racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bankovni_racun()
        {
            this.Transakcija = new HashSet<Transakcija>();
            this.Transakcija_investicije = new HashSet<Transakcija_investicije>();
        }
    
        public string iban { get; set; }
        public int id_vrsta_racuna { get; set; }
        public int id_korisnik { get; set; }
        public string naziv_racuna { get; set; }
        public Nullable<decimal> stanje_racuna { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Vrsta_racuna Vrsta_racuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcija> Transakcija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcija_investicije> Transakcija_investicije { get; set; }
    }
}
