//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocetniZaslon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investicijski_portfolio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Investicijski_portfolio()
        {
            this.Transakcija_investicije = new HashSet<Transakcija_investicije>();
        }
    
        public int id_portfolia { get; set; }
        public int id_korisnik { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcija_investicije> Transakcija_investicije { get; set; }
    }
}
