//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocetniZaslon
{
    using System;
    using System.Collections.Generic;
    
    public partial class investicija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public investicija()
        {
            this.stanje_investicije = new HashSet<stanje_investicije>();
            this.transakcija_investicije = new HashSet<transakcija_investicije>();
        }
    
        public int id_investicije { get; set; }
        public int id_vrsta_investicije { get; set; }
        public string naziv_investicije { get; set; }
    
        public virtual vrsta_investicije vrsta_investicije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stanje_investicije> stanje_investicije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transakcija_investicije> transakcija_investicije { get; set; }
    }
}
