//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocetniZaslon
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategorije_transakcije
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kategorije_transakcije()
        {
            this.transakcija = new HashSet<transakcija>();
        }
    
        public int id_kategorije_transakcije { get; set; }
        public int id_vrsta_transakcije { get; set; }
        public string naziv_kategorije { get; set; }
    
        public virtual vrsta_transakcije vrsta_transakcije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transakcija> transakcija { get; set; }
    }
}
