//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocetniZaslon
{
    using System;
    using System.Collections.Generic;
    
    public partial class transakcija_investicije
    {
        public int id_transakcije_investicije { get; set; }
        public int id_vrsta_transakcije { get; set; }
        public string iban { get; set; }
        public int id_investicije { get; set; }
        public int id_portfolia { get; set; }
        public Nullable<decimal> iznos_transakcije_investicije { get; set; }
        public Nullable<System.DateTime> datum_transakcije_investicije { get; set; }
        public int kolicina_investicije { get; set; }
    
        public virtual investicija investicija { get; set; }
        public virtual investicijski_portfolio investicijski_portfolio { get; set; }
        public virtual vrsta_transakcije vrsta_transakcije { get; set; }
    }
}
