//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocetniZaslon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcija_investicije
    {
        public int id_transakcije_investicije { get; set; }
        public int id_vrsta_transakcije { get; set; }
        public string iban { get; set; }
        public int id_investicije { get; set; }
        public int id_portfolia { get; set; }
        public Nullable<decimal> iznos_transakcije_investicije { get; set; }
        public Nullable<System.DateTime> vrijeme_transakcije_investicije { get; set; }
        public decimal kolicina_investicije { get; set; }
    
        public virtual Investicija Investicija { get; set; }
        public virtual Investicijski_portfolio Investicijski_portfolio { get; set; }
        public virtual Vrsta_transakcije Vrsta_transakcije { get; set; }
        public virtual Bankovni_racun Bankovni_racun { get; set; }
    }
}
