//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocetniZaslon
{
    using System;
    using System.Collections.Generic;
    
    public partial class transakcija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transakcija()
        {
            this.transakcija1 = new HashSet<transakcija>();
            this.kategorije_transakcije = new HashSet<kategorije_transakcije>();
        }
    
        public int id_transakcije { get; set; }
        public string iban { get; set; }
        public decimal iznos_transakcije { get; set; }
        public Nullable<System.DateTime> datum_transakcije { get; set; }
        public string opis_transakcije { get; set; }
        public string lokacija_slike_racuna { get; set; }
        public Nullable<int> id_vlastite_transakcije { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transakcija> transakcija1 { get; set; }
        public virtual transakcija transakcija2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kategorije_transakcije> kategorije_transakcije { get; set; }
    }
}
