//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocetniZaslon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WalletEntities : DbContext
    {
        public WalletEntities()
            : base("name=WalletEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bankovni_racun> Bankovni_racun { get; set; }
        public virtual DbSet<Investicija> Investicija { get; set; }
        public virtual DbSet<Investicijski_portfolio> Investicijski_portfolio { get; set; }
        public virtual DbSet<Kategorije_transakcije> Kategorije_transakcije { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Stanje_investicije> Stanje_investicije { get; set; }
        public virtual DbSet<Transakcija> Transakcija { get; set; }
        public virtual DbSet<Transakcija_investicije> Transakcija_investicije { get; set; }
        public virtual DbSet<Vrsta_investicije> Vrsta_investicije { get; set; }
        public virtual DbSet<Vrsta_racuna> Vrsta_racuna { get; set; }
        public virtual DbSet<Vrsta_transakcije> Vrsta_transakcije { get; set; }
    }
}
