//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocetniZaslon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bankovni_racun> bankovni_racun { get; set; }
        public virtual DbSet<investicija> investicija { get; set; }
        public virtual DbSet<investicijski_portfolio> investicijski_portfolio { get; set; }
        public virtual DbSet<kategorije_transakcije> kategorije_transakcije { get; set; }
        public virtual DbSet<korisnik> korisnik { get; set; }
        public virtual DbSet<stanje_investicije> stanje_investicije { get; set; }
        public virtual DbSet<transakcija> transakcija { get; set; }
        public virtual DbSet<transakcija_investicije> transakcija_investicije { get; set; }
        public virtual DbSet<vrsta_investicije> vrsta_investicije { get; set; }
        public virtual DbSet<vrsta_racuna> vrsta_racuna { get; set; }
        public virtual DbSet<vrsta_transakcije> vrsta_transakcije { get; set; }
    }
}
